stages:
  setup:
    cmd:
    - uv venv
    - uv sync --locked
    always_changed: true
  spider-mawilabv1_1:
    cmd: uv run python -m mawiflow.scraper mawilabv1.1
    deps:
    - .python-version
    - pyproject.toml
    - src/mawiflow/scraper
    - uv.lock
    outs:
    - data/raw/mawilabv1.1_spider.yaml:
        persist: true
    frozen: true
  generate-annotations:
    cmd: sbatch --wait generate-annotations.sh
    deps:
    - params.yaml
    - data/raw/
    - .python-version
    - pyproject.toml
    - uv.lock
    - generate-annotations.sh
    - src/mawiflow/annotations
    outs:
    - data/annotations/
  cicflowmeter-image:
    cmd: apptainer build cicflowmeter.sif
      docker://docker.io/thelurps/gintsengelen-cicflowmeter:4dd5319
    outs:
    - cicflowmeter.sif
  generate-flows:
    foreach: ${recordings}
    do:
      cmd: sbatch generate-flows.sh ${item}
      deps:
      - cicflowmeter.sif
      - generate-flows.sh
  combine-flows-with-annotations:
    cmd: sbatch --wait combine-flows-with-annotations.sh
    deps:
    - params.yaml
    - data/annotations/
    #- data/cicflowmeter/
    - .python-version
    - pyproject.toml
    - uv.lock
    - combine-flows-with-annotations.sh
    - src/mawiflow/flows
    outs:
    - data/flows/
